#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_USER: #@ data.values.postgres.user
  POSTGRES_PASSWORD: #@ data.values.postgres.password
  POSTGRES_PORT: '5432'
  POSTGRES_HOST: 'postgres.backstage.svc.cluster.local'
