apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: ${{ values.name | safe }}
spec:
  title: ${{ values.title }}
  description: ${{ values.description }}
  publish:
    image: '$(image_repository)/${{ values.repoName | safe }}-files:$(workshop_version)'
  workshop:
    files:
      - image:
          url: '$(image_repository)/${{ values.repoName | safe }}-files:$(workshop_version)'
        includePaths:
          - /workshop/**
          - /exercises/**
          - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
