#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backstage
type: Opaque
data:
  app-config.production.yaml: #@ yaml.encode(data.values.app_config)
