#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: #@ base64.encode(data.values.github_token)
  AUTH_GITHUB_CLIENT_ID: #@ base64.encode(data.values.auth.github.client_id)
  AUTH_GITHUB_CLIENT_SECRET: #@ base64.encode(data.values.auth.github.client_secret)
